### ISSUE TITLE
How do I apply an array of latitudes and longitudes to display multiple push pins? 

### ISSUE THREAD

**Issue by nikoma** [Credera/angular-bing-maps#26]
My web service returns an array of location objects. How can I use them with ng-repeat="loc in locations" to create multiple pushpins?

**Comment by sjmorrow** [comment]
You can use ng-repeat on the pushpin directive, and set the lat and lng attributes on the pushpin from your "loc" model. So making some assumptions on your data structure, it would look like this
```html
<pushpin ng-repeat="loc in locations" lat="loc.latitude" lng="loc.longitude"></pushpin>
```

**Comment by akanieski** [comment]
I get the following error when using ng-repeat in the following way:
```

                    <bing-map 
                              mapType="mapType"
                              zoom="mapZoom"
                              options="options"
                              credentials="credentials" 
                              center="mapCenter">

                        <pushpin ng-repeat="airport in airports" lat="airport.location.Latitude" lng="airport.location.Longitude"></pushpin>
                    </bing-map>
```


```
TypeError: Cannot read property 'latitude' of undefined
    at Object.ut.contains (http://ecn.dev.virtualearth.net/mapcontrol/v7.0/7.0.20150902134620.61/js/en-us/veapicore.js:3:6915)
    at et (http://ecn.dev.virtualearth.net/mapcontrol/v7.0/7.0.20150902134620.61/js/en-us/veapicore.js:1:92013)
    at Object.oi [as handler] (http://ecn.dev.virtualearth.net/mapcontrol/v7.0/7.0.20150902134620.61/js/en-us/veapicore.js:1:89035)
    at n.invoke (http://ecn.dev.virtualearth.net/mapcontrol/v7.0/7.0.20150902134620.61/js/en-us/veapicore.js:3:9888)
    at e (http://ecn.dev.virtualearth.net/mapcontrol/v7.0/7.0.20150902134620.61/js/en-us/veapicore.js:1:51920)
    at Object.push (http://ecn.dev.virtualearth.net/mapcontrol/v7.0/7.0.20150902134620.61/js/en-us/veapicore.js:1:52344)
    at link (http://127.0.0.1:3000/libs/angular-bing-maps.js:468:42)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-beta.1/angular.min.js:73:493
    at ca (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-beta.1/angular.min.js:74:47)
    at M (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-beta.1/angular.min.js:62:291) <pushpin ng-repeat="airport in airports" lat="airport.location.Latitude" lng="airport.location.Longitude" class="ng-scope ng-isolate-scope">
```

**Comment by sjmorrow** [comment]
@akanieski This is usually caused by your model being undefined. Have you verified that airport.location.Latitude is defined? Also, if your scope is instantiated with an empty / null value for your lat / lngs, then on your first digest cycle, you will get these errors you are seeing.

In other words, make sure airport.location.Latitude is not undefined

**Comment by akanieski** [comment]
Yeah I think that was it. Thanks.



—
